import { Type } from './types'

export const technologies: Content.Technology[] = [
    {
        id: 'react',
        name: 'React',
        type: Type.Library,
        icon: 'react',
    },
    {
        id: 'typescript',
        name: 'TypeScript',
        type: Type.Language,
        icon: 'typescript',
    },
    {
        id: 'javascript',
        name: 'JavaScript',
        type: Type.Language,
        icon: 'javascript',
    },
    {
        id: 'nodejs',
        name: 'Node.js',
        type: Type.Framework,
        icon: 'nodejs',
    },
    {
        id: 'springboot',
        name: 'Spring Boot',
        type: Type.Framework,
        icon: 'spring',
    },
    {
        id: 'java',
        name: 'Java',
        type: Type.Language,
        icon: 'java',
    },
    {
        id: 'php',
        name: 'PHP',
        type: Type.Language,
        icon: 'php',
    },
    {
        id: 'symfony',
        name: 'Symfony',
        type: Type.Framework,
        icon: 'symfony not-colored',
    },
    {
        id: 'mysql',
        name: 'MySQL',
        type: Type.Database,
        icon: 'mysql',
    },
    {
        id: 'postgresql',
        name: 'PostgreSQL',
        type: Type.Database,
        icon: 'postgresql',
    },
    {
        id: 'mongodb',
        name: 'MongoDB',
        type: Type.Database,
        icon: 'mongodb',
    },
    {
        id: 'docker',
        name: 'Docker',
        type: Type.Devops,
        icon: 'docker',
    },
    {
        id: 'markdown',
        name: 'Markdown',
        type: Type.Language,
        icon: 'markdown',
    },
    {
        id: 'html',
        name: 'HTML',
        type: Type.Language,
        icon: 'html5',
    },
    {
        id: 'css',
        name: 'CSS',
        type: Type.Language,
        icon: 'css3',
    },
    {
        id: 'sass',
        name: 'Sass',
        type: Type.Language,
        icon: 'sass',
    },
    {
        id: 'python',
        name: 'Python',
        type: Type.Language,
        icon: 'python',
    },
    {
        id: 'csharp',
        name: 'C#', 
        type: Type.Language,
        icon: 'csharp',
    },
    {
        id: 'c',
        name: 'C',
        type: Type.Language,
        icon: 'c',
    },
    {
        id: 'rust',
        name: 'Rust',
        type: Type.Language,
        icon: 'rust',
    },
    {
        id: 'bash',
        name: 'Bash',
        type: Type.Language,
        icon: 'bash',
    },
    {
        id: 'powershell',
        name: 'PowerShell',
        type: Type.Language,
        icon: 'https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_powershell_icon_130243.png',
    },
    {
        id: 'go',
        name: 'Go',
        type: Type.Language,
        icon: 'go',
    },
    {
        id: 'git',
        name: 'Git',
        type: Type.Tool,
        icon: 'git',
    },
    {
        id: 'github',
        name: 'GitHub',
        type: Type.Tool,
        icon: 'github not-colored',
    },
    {
        id: 'android-studio',
        name: 'Android Studio',
        type: Type.Tool,
        icon: 'androidstudio',
    },
    {
        id: 'jetbrains',
        name: 'JetBrains',
        type: Type.Tool,
        icon: 'jetbrains',
    },
    {
        id: 'vsc',
        name: 'Visual Studio Code',
        type: Type.Tool,
        icon: 'vscode',
    },
    {
        id: 'postman',
        name: 'Postman',
        type: Type.Tool,
        icon: 'https://img.uxwing.com/wp-content/themes/uxwing/download/brands-social-media/postman-icon.png',
    },
    {
        id: 'unity',
        name: 'Unity',
        type: Type.Tool,
        icon: 'unity',
    },
    {
        id: 'linux',
        name: 'Linux',
        type: Type.Tool,
        icon: 'linux',
    },
    {
        id: 'windows',
        name: 'Windows',
        type: Type.Tool,
        icon: 'windows8',
    },
    {
        id: 'seo',
        name: 'SEO',
        type: Type.Tool,
        icon: 'https://www.freeiconspng.com/thumbs/seo-icon-png/search-engine-optimization-icon-7.png',
    },
    {
        id: 'express',
        name: 'Express',
        type: Type.Library,
        icon: 'express',
    },
    {
        id: 'fastify',
        name: 'Fastify',
        type: Type.Library,
        icon: 'https://www.svgrepo.com/show/306030/fastify.svg',
    },
    {
        id: 'vite',
        name: 'Vite',
        type: Type.Library,
        icon: 'https://www.svgrepo.com/show/374167/vite.svg',
    },
    {
        id: 'nextjs',
        name: 'Next.js',
        type: Type.Framework,
        icon: 'nextjs',
    },
    {
        id: 'trpc',
        name: 'tRPC',
        type: Type.Library,
        icon: 'https://trpc.io/img/logo.svg',
    },
    {
        id: 'gatsby',
        name: 'Gatsby',
        type: Type.Framework,
        icon: 'gatsby',
    },
    {
        id: 'angular',
        name: 'Angular',
        type: Type.Framework,
        icon: 'angularjs',
    },
    {
        id: 'astro',
        name: 'Astro',
        type: Type.Framework,
        icon: 'https://bestofjs.org/logos/astro.dark.svg',
    },
    {
        id: 'strapi',
        name: 'Strapi',
        type: Type.Tool,
        icon: 'https://static-00.iconduck.com/assets.00/strapi-icon-512x505-3hl7a1v3.png',
    },
    {
        id: 'photoshop',
        name: 'Photoshop',
        type: Type.Tool,
        icon: 'photoshop',
    },
    {
        id: 'premiere-pro',
        name: 'Premiere Pro',
        type: Type.Tool,
        icon: 'premierepro',
    },
    {
        id: 'figma',
        name: 'Figma',
        type: Type.Tool,
        icon: 'figma',
    },
    {
        id: 'rocket',
        name: 'Rocket.rs',
        type: Type.Library,
        icon: 'https://www.iconpacks.net/icons/1/free-rocket-launch-icon-1190-thumb.png',
    },
    {
        id: 'storybook',
        name: 'Storybook',
        type: Type.Tool,
        icon: 'storybook',
    },
    {
        id: 'svelte',
        name: 'Svelte',
        type: Type.Framework,
        icon: 'svelte',
    },
    {
        id: 'ansible',
        name: 'Ansible',
        type: Type.Devops,
        icon: 'ansible not-colored',
    },
    {
        id: 'azure',
        name: 'Azure',
        type: Type.Devops,
        icon: 'azure',
    },
    {
        id: 'chakra-ui',
        name: 'Chakra UI',
        type: Type.Library,
        icon: 'https://www.coffeeclass.io/logos/chakra-ui.png',
    },
    {
        id: 'prisma',
        name: 'Prisma',
        type: Type.Library,
        icon: 'https://plugins.jetbrains.com/files/14282/146547/icon/pluginIcon.png',
    },
    {
        id: 'vitest',
        name: 'Vitest',
        type: Type.Library,
        icon: 'https://seeklogo.com/images/V/vitest-logo-9ADDA575A5-seeklogo.com.png',
    }
]