name: Deploy (SSH)

on:
    push:
        branches: [main]
    # allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:

    build:
        uses: ./.github/workflows/build.yml

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                name: static-website

            - name: Debug
              run: ls -la

            - name: Deploy to VPS using SCP
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.HOST }}
                port: ${{ secrets.PORT }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                source: ./*
                target: ${{ secrets.VPS_PROJECT_PATH }}